pack-format = "packwiz:1.1.0"
name = "CobbleCreate"
author = "Pavle012"
version = "1.5"
description = "Pokemon with Create - A curated modpack blending Create engineering with Cobblemon"

[index]
file = "modrinth.index.json"
hash-format = "sha512"
hash = ""

[versions]
minecraft = "1.21.1"
